implemented the command line parser to read the stock ticker which is…
ECE-421/Project1-Stock_market_monitor pull request #2
Opened 2024-02-03 23:40 UTC by iDeniyi

… passed as a command line argument. Also implemented the functionalities to validate the stock ticker

2024-02-06 06:37 UTC, dheadrick1618 requested changes
Ron taught me a while back that you should only ever explicitly include files when committing. Never use ' git add .  '  It prevents things like the info.json file you have to get tossed in, when its just a random build file. 

Other than that looks good!

2024-02-06 06:37 UTC, dheadrick1618 commented on stock_monitor/target/.rustc_info.json
Please remove this file. Not sure why the .gitignore isn't working with this. Ill add  this explicitly to the gitignore . Same is happening with me.

2024-02-06 21:31 UTC, iDeniyi commented
I believe it's fixed now.

2024-02-09 01:00 UTC, Koss24 requested changes

2024-02-09 01:00 UTC, Koss24 commented on stock_monitor/src/command_line_parser.rs
> +pub fn check_stock_ticker(ticker: String) -> bool {
Do we need a String as parameter here we use a string pointer every else. It doesn't look like the String is being modified here so I don't think we need it be mutable and a pointer is fine

2024-02-15 04:44 UTC, merged