Command parasing with api
ECE-421/Project1-Stock_market_monitor pull request #3
Opened 2024-02-09 01:38 UTC by Koss24

Merged together command line parsing and yahoo api

2024-02-12 18:37 UTC, dheadrick1618 requested changes
This is spitting out 'Error: FetchFailed ' when I give it a bad stock ticker. I wonder if we should instead be prompting the user to enter a new ticker and keep the program in a loop unless they exit? The project outline says the program cant' crash when given a bad stock symobl, so although its not technically crashing I think this give the appearance that the program isnt working properly .

2024-02-12 19:12 UTC, Koss24 commented
Added a new commit, just removed the error println and handling the empty quotes in main.rs to inform the user of a potentially wrong or non-existent ticker

2024-02-15 04:44 UTC, dheadrick1618 approved these changes

2024-02-15 04:44 UTC, dheadrick1618 commented on gitignore.txt:Zone.Identifier
What is this for?

2024-02-15 04:44 UTC, merged